
# Model hyperparameters
model_name : name
ckpt_save_path : ./ckpts/
ckpt_path : ./ckpts/check.ckpt
report_path : ./reports/
learning_rate: 0.001
batch_size: 16
num_epochs: 50
gamma : 0.7
step_size : 4
ckpt_save_freq : 1
num_layer : 5
teacher_forcing : 0.8
dropout : 0

# Dataset parameters
dataset:
  path: ./datasets/landscapes/
